@startuml package-mastermind
title Package kodenix.mastermind 

package kodenix.mastermind.views {
    class View {
        +View(:Game)
        +init()
    }
    class StartView {
        +StartView()
        ~show(): void
    }
    class ResumeView {
        +ResumeView(:Game)
        ~isResumed(): boolean
    }
    class GameView {
        +GameView(:Game)
        ~interact(): void
    }
    class AttemptView {
        +AttemptView(:Game)
        ~interact(): void
    }
    class Message {
        +TITLE
        +RESUME_QUESTION
        +RESPONSE_YES
        +RESPONSE_NOT
        +PROPOSE_COMBINATION
        -message: String;
        -Message(String)
    }
    
    View *-down-> StartView
    View *-down-> GameView
    View *-down-> ResumeView
    GameView *-down-> AttemptView
    GameView .down.> kodenix.utils.Console
    StartView .down.> kodenix.utils.Console
    StartView .down.> Message
    ResumeView .down.> Message
    AttemptView .down.> Message
    AttemptView .down.> kodenix.utils.Console

    
    View o--> kodenix.mastermind.models.Game
    GameView o--> kodenix.mastermind.models.Game
    ResumeView o--> kodenix.mastermind.models.Game
    AttemptView o--> kodenix.mastermind.models.Game
}

package kodenix.mastermind.models {
    class Game {
        -attempts: ArrayList<Attempt>
        +reset(): void
        +hasWinner(): boolean
        +hasLosser(): boolean
        +getAttemptsSize(): int
    }
}

package kodenix.utils {
    class Console {
        +write(promptMessage : string) : void
        +read(promptMessage : string) : string
    }
}




@enduml